### PR TITLE
Fixed JVM reporter being non transparent

### PR DESCRIPTION
**Pull request by hanny24**

### CODE REVIEW

**Comment by tomasherman** [comment]
Can you elaborate on what is changing and why?

**Comment by hanny24** [comment]
Basically whenever you access a bean you need to wrap it inside an effect. Otherwise it might lead To vegy ugly bugs

**Comment by hanny24** [comment]
> Would it be possible to change the pr to make less changes? I'm on phone and have hard time distill what is actually changing

Sorry, but not really.

**Comment by tomasherman** [comment]
> Basically whenever you access a bean you need to wrap it inside an effect. Otherwise it might lead To vegy ugly bugs

can you pls elaborate? how does wrapping it in effect help? Im not opposed to this, just trying to get some understanding of what is happening

**Comment by hanny24** [comment]
Example:
```scala
val getHeapUsedIO: F[Unit] = heapUsed.set(memoryBean.getHeapMemoryUsage.getUsed)
```
This will set the metric value to the same value every time it's evaluated.

**Comment by tomasherman** [comment]
ah, i think i get it ... i wonder if we should change api of gauge to accept `F[Long]` as paramter instead of `Long`

**Comment by tomasherman** [comment]
i wonder if api on all of the methods should be wrapped in F ... the way it is done right now seems fairly error prone ... lets discuss in person tomorrow

**Comment by tomasherman** [comment]
but we don't have to block this and merge this - just pls update the changelog

**Pull request merged**
